#!/usr/bin/env python3
"""Generate src/CallSites_G.inc with the call sites we hook for Approach G.

v0.14 (this version): five targets covering all known LockB-bracketing
entry points -

    id 19369 (RVA 0x296c00) - takes LockA, descends to LockB.
    id 40285 (RVA 0x6d37b0) - direct lea LockB, brackets internally.
    id 40333 (RVA 0x6d9720) - direct lea LockB, brackets internally.
    id 40334 (RVA 0x6d9890) - direct lea LockB, brackets internally.
    id 40706 (RVA 0x6ef230) - indirect [this+0x150]; narrow case is LockB.

id 40335 is the BSSpinLock acquire/release primitive specialised for
LockB (parameterised by DL); it does not bracket and is intentionally
NOT hooked here. If AB-BA recurs through id 40335 callers we will hook
those callers instead in a follow-up.

Hooking every direct CALL/JMP site to these five and wrapping the call
in one shared std::recursive_mutex serialises every entry to the
LockA / LockB region. AB-BA cannot form because no thread can hold
LockB without first holding the mutex.
"""
import bisect
import sys
from pathlib import Path

import capstone

sys.path.insert(0, str(Path(__file__).parent))
from xref_calls import parse_pe
from addrlib_lookup import parse

EXE = Path(r"D:\SPIELE\nolvus\Instances\Nolvus Awakening\STOCK GAME\SkyrimSE.exe.unpacked.exe")
ADDRLIB = Path(r"D:\SPIELE\nolvus\Instances\Nolvus Awakening\MODS\mods\Address Library for SKSE Plugins\SKSE\Plugins\version-1-5-97-0.bin")
OUT = Path(__file__).resolve().parent.parent / "skyrim-freeze-fix" / "src" / "CallSites_G.inc"

TARGETS = {
    0x296c00: ("19369", "id_19369"),
    0x6d37b0: ("40285", "id_40285"),
    0x6d9720: ("40333", "id_40333"),
    0x6d9890: ("40334", "id_40334"),
    0x6ef230: ("40706", "id_40706"),
}


def main() -> int:
    data, image_base, sections = parse_pe(EXE)
    text = next(s for s in sections if s[0] == ".text" and s[2] > 0x100000)
    _, va, _, raw_off, raw_size = text
    blob = data[raw_off:raw_off + raw_size]

    _, _, entries = parse(ADDRLIB)
    by_off = sorted(entries, key=lambda e: e[1])
    offsets = [e[1] for e in by_off]
    ids_for_off = [e[0] for e in by_off]

    def nearest(rva: int):
        i = bisect.bisect_right(offsets, rva) - 1
        if i < 0:
            return (0, 0)
        return (ids_for_off[i], rva - offsets[i])

    md = capstone.Cs(capstone.CS_ARCH_X86, capstone.CS_MODE_64)
    md.detail = True
    md.skipdata = True

    matches = {tgt: [] for tgt in TARGETS}
    for ins in md.disasm(blob, image_base + va):
        if ins.mnemonic not in ("call", "jmp"):
            continue
        if len(ins.bytes) != 5:
            continue
        if ins.bytes[0] not in (0xE8, 0xE9):
            continue
        try:
            ops = ins.operands
        except capstone.CsError:
            continue
        if len(ops) != 1 or ops[0].type != capstone.x86.X86_OP_IMM:
            continue
        target_rva = ops[0].imm - image_base
        if target_rva in TARGETS:
            site_rva = ins.address - image_base
            kind = "kCall" if ins.bytes[0] == 0xE8 else "kJmp "
            matches[target_rva].append((site_rva, kind))

    lines = [
        "// AUTO-GENERATED by analysis/gen_callsites_g_inc.py - DO NOT EDIT.",
        "//",
        "// Direct CALL (E8 rel32) and tail-call JMP (E9 rel32) sites of",
        "// id 19369, id 40285, id 40333, id 40334 and id 40706 in",
        "// SkyrimSE.exe v1.5.97.",
        "//",
        "// Indirect calls are not enumerated. Static analysis of these",
        "// functions shows none is a virtual method (no occurrence of",
        "// `call qword [rax + offset]` style dispatch with a plausible",
        "// vtable target reaching their entries), so direct CALLs are",
        "// expected to cover all entries. The recursion site at",
        "// id 19369 +0x9d is included in the table because it is also a",
        "// direct CALL; recursion is handled by std::recursive_mutex on",
        "// the wrapper side.",
        "",
    ]
    for tgt_rva, (id_str, label) in TARGETS.items():
        sites = sorted(matches[tgt_rva])
        lines.append(f"// id {id_str} ({label}): {len(sites)} site(s)")
        lines.append(f"constexpr CallSite kCallSites_{id_str}[] = {{")
        for site_rva, kind in sites:
            sym_id, delta = nearest(site_rva)
            lines.append(f"    {{ {sym_id:>6d}, 0x{delta:04x}, {kind} }},  "
                         f"// 0x{site_rva:08x}")
        lines.append("};")
        lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT}: {sum(len(v) for v in matches.values())} sites total")
    return 0


if __name__ == "__main__":
    sys.exit(main())
