#!/usr/bin/env python3
"""Generate src/CallSites.inc from a CALL/JMP scan of SkyrimSE.exe.

Targets BSSpinLock::Acquire (id 12210, RVA 0x132bd0) and
BSSpinLock::Release (id 66983, RVA 0xc075a0).
"""
import bisect
import sys
from pathlib import Path

import capstone

sys.path.insert(0, str(Path(__file__).parent))
from xref_calls import parse_pe
from addrlib_lookup import parse

EXE = Path(r"D:\SPIELE\nolvus\Instances\Nolvus Awakening\STOCK GAME\SkyrimSE.exe.unpacked.exe")
ADDRLIB = Path(r"D:\SPIELE\nolvus\Instances\Nolvus Awakening\MODS\mods\Address Library for SKSE Plugins\SKSE\Plugins\version-1-5-97-0.bin")
OUT = Path(__file__).resolve().parent.parent / "skyrim-freeze-fix" / "src" / "CallSites.inc"

TARGETS = {
    0x132bd0: ("12210", "Acquire"),
    0xc075a0: ("66983", "Release"),
}


def main() -> int:
    data, image_base, sections = parse_pe(EXE)
    text = next(s for s in sections if s[0] == ".text" and s[2] > 0x100000)
    _, va, _, raw_off, raw_size = text
    blob = data[raw_off:raw_off + raw_size]

    _, _, entries = parse(ADDRLIB)
    by_off = sorted(entries, key=lambda e: e[1])
    offsets = [e[1] for e in by_off]
    ids_for_off = [e[0] for e in by_off]

    def nearest(rva: int):
        i = bisect.bisect_right(offsets, rva) - 1
        if i < 0:
            return (0, 0)
        return (ids_for_off[i], rva - offsets[i])

    md = capstone.Cs(capstone.CS_ARCH_X86, capstone.CS_MODE_64)
    md.detail = True
    md.skipdata = True

    matches = {tgt: [] for tgt in TARGETS}
    for ins in md.disasm(blob, image_base + va):
        if ins.mnemonic not in ("call", "jmp"):
            continue
        if len(ins.bytes) != 5:
            continue
        if ins.bytes[0] not in (0xE8, 0xE9):
            continue
        try:
            ops = ins.operands
        except capstone.CsError:
            continue
        if len(ops) != 1 or ops[0].type != capstone.x86.X86_OP_IMM:
            continue
        target_rva = ops[0].imm - image_base
        if target_rva in TARGETS:
            site_rva = ins.address - image_base
            kind = "kCall" if ins.bytes[0] == 0xE8 else "kJmp "
            matches[target_rva].append((site_rva, kind))

    lines = [
        "// AUTO-GENERATED by analysis/gen_callsites_inc.py - DO NOT EDIT.",
        "//",
        "// Direct CALL (E8 rel32) and tail-call JMP (E9 rel32) sites of",
        "// BSSpinLock::Acquire (id 12210) and BSSpinLock::Release (id 66983)",
        "// in SkyrimSE.exe v1.5.97. Indirect calls are not enumerated.",
        "",
    ]
    for tgt_rva, (id_str, label) in TARGETS.items():
        sites = sorted(matches[tgt_rva])
        lines.append(f"// id {id_str} ({label}): {len(sites)} site(s)")
        lines.append(f"constexpr CallSite kCallSites_{id_str}[] = {{")
        for site_rva, kind in sites:
            sym_id, delta = nearest(site_rva)
            lines.append(f"    {{ {sym_id:>6d}, 0x{delta:04x}, {kind} }},  "
                         f"// 0x{site_rva:08x}")
        lines.append("};")
        lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT}: {sum(len(v) for v in matches.values())} sites total")
    return 0


if __name__ == "__main__":
    sys.exit(main())
